#!/usr/bin/env bash

set -exuo pipefail

PR=${1:-}

# checkout pr
gh pr checkout "${PR}"

# fetch origin
git fetch origin

# get base branch
base_branch=$(gh pr view --json baseRefName --template '{{.baseRefName}}')

# rebase onto origin/{base}
git rebase "origin/${base_branch}"
